travis:
  secure:
    BINSTAR_TOKEN: ZkfvF3Hb68lof59EDQ+PvzVEnnmJwt0rNT8Ll4TbqG5uk91IASDTolIcUIrzjmdh11kHvu+Q0er+FdtX1XIbG41PO6q+JOlRDGleLi+Fwu7wn9fCG/VEpnS0fadvh1IQiQPG20ONA8ANBafpULLMp37RgnFmqQeHv6gcySw9GIYe5YgNLCiZw1ybwOXocvV2xYVFYgL7s3daqzLUum9mGHQ2qL0wpRJ6QgWlIydQekyNLCZF7nzmRazGENJtAUHr/fl++U4SUpRNiDxN0cPkdMZcbw7Hi/N6iZK+BDIBH3BIuRPJPrt0oou9uQUQNH+Q+gA6/mzCJiGNw597pV5+pZzCsgBqyxLUKxl2HhgidGpKOT3sSsT+4F068R4EExDy3hSeuZMooG16inqPKnyLouIrfLKRzhcc8ojRzfAy6btlRgLWwqnCD6fmM9cGxF+KymXDuRLpcUwQ5XJMypnBiUCpuJGu0Ga25AM0QQ2jwX5z3ANGxQDMyPT6eFF7JHZbtZkbvTlN0etXDOkBQN91bMvdUQB3VuGt0BBieR+qzgvPT+9XJWp5Z7g5So/oYwaAALPlGQpnXr5lVODJiiAU9zqDOyW6ygjxMAraNkWqTy0SHEWMy0jgjgk83bwrqH8e3kS+RDHRsUfk556iV/I6Y8rRN5zzBoRQ7tlk3dDU7kE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
