travis:
  secure:
    BINSTAR_TOKEN: WraC+145+RtLHC3NXsycrVw2rFGcLWI9+RVxzEsSRwLebOlMxJ7bPq8Eafr0Ga+9wG9Mkab7E6xeq3DtMbmrY1WJBpE1B9wKe2+nybJojDJbpplZ+DFrZyGkVAgg3/A1Q6BfBTGy1ZD8oCRnbRZ16GNyBY6nZYRHq1mfHBmf/r/cfUscr48fi5JReqtykAsAy9AubVHVEEZ4cklkQwmxxa05d0JbybmWPcqN7k/i5Mbjh0F/X9Ref8K63QzcZ8pXaWgcDVWGxiRzHEmgh22rZerNgIAsroj8UaEO/rn90GWPhE9PeUPKZnifeBXpDZkkPPwlbqk5WylwtxxcX1mNGkfCqXktJ7jc/sdsMmtc2K3OtYXv02Cu0Gzuf2JMf2pWu6BF3k+/9qC46uIYs3HXfHLnV+xOBYMJoX/ODh3xJwwgJIoq6tdUJhzJBdMZatBII8lby6MR7IVPWaQ1prbzYdmb2y5Yvw9FVDvdkn4bH6wcW9vSeLlR01SrJBT394cZkrQ2U3WzU+UIMt2Jb5PcNBzNJ7j1CABrXF5kjBUooIL6mqTVVYC0Ff9Wr0ptNK6eu+rMUGgLDHsmK4t+UzSKB53PVkjBVHSTkJ+D/lVr6FgaTiigHvaK3gRwbRFvFJ5qgZ70EFCO5vA/xtFvVhi5rG5l+c8T+jjvsomHeUBwyTk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
